version: '3.8'
services:

    # Application
    app:
        build:
            context: .
            dockerfile: app.Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database"
    # Web Server
    web:
        build:
            context: .
            dockerfile: web.Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 80:80
    # Database
    database:
        image: mariadb:10.5
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 33061:3306
volumes:
    dbdata:
